// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// update_A_inv_C
Eigen::MatrixXd update_A_inv_C(Eigen::MatrixXd a, Eigen::MatrixXd new_x, bool leftNode);
RcppExport SEXP _forestryR_update_A_inv_C(SEXP aSEXP, SEXP new_xSEXP, SEXP leftNodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type a(aSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type new_x(new_xSEXP);
    Rcpp::traits::input_parameter< bool >::type leftNode(leftNodeSEXP);
    rcpp_result_gen = Rcpp::wrap(update_A_inv_C(a, new_x, leftNode));
    return rcpp_result_gen;
END_RCPP
}
// update_S_k
Eigen::MatrixXd update_S_k(Eigen::MatrixXd prev, Eigen::MatrixXd next_obs, double next_y, bool left);
RcppExport SEXP _forestryR_update_S_k(SEXP prevSEXP, SEXP next_obsSEXP, SEXP next_ySEXP, SEXP leftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type prev(prevSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type next_obs(next_obsSEXP);
    Rcpp::traits::input_parameter< double >::type next_y(next_ySEXP);
    Rcpp::traits::input_parameter< bool >::type left(leftSEXP);
    rcpp_result_gen = Rcpp::wrap(update_S_k(prev, next_obs, next_y, left));
    return rcpp_result_gen;
END_RCPP
}
// update_G_k
Eigen::MatrixXd update_G_k(Eigen::MatrixXd prev, Eigen::MatrixXd next_obs, bool left);
RcppExport SEXP _forestryR_update_G_k(SEXP prevSEXP, SEXP next_obsSEXP, SEXP leftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type prev(prevSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type next_obs(next_obsSEXP);
    Rcpp::traits::input_parameter< bool >::type left(leftSEXP);
    rcpp_result_gen = Rcpp::wrap(update_G_k(prev, next_obs, left));
    return rcpp_result_gen;
END_RCPP
}
// compute_Best_RSS
Eigen::VectorXd compute_Best_RSS(Eigen::Map<Eigen::MatrixXd> training_data, double lambda, int splitting_feat, Eigen::Map<Eigen::VectorXd> linear_features);
RcppExport SEXP _forestryR_compute_Best_RSS(SEXP training_dataSEXP, SEXP lambdaSEXP, SEXP splitting_featSEXP, SEXP linear_featuresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type training_data(training_dataSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type splitting_feat(splitting_featSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type linear_features(linear_featuresSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Best_RSS(training_data, lambda, splitting_feat, linear_features));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_forestryR_update_A_inv_C", (DL_FUNC) &_forestryR_update_A_inv_C, 3},
    {"_forestryR_update_S_k", (DL_FUNC) &_forestryR_update_S_k, 4},
    {"_forestryR_update_G_k", (DL_FUNC) &_forestryR_update_G_k, 3},
    {"_forestryR_compute_Best_RSS", (DL_FUNC) &_forestryR_compute_Best_RSS, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_forestryR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
