# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
update_A_inv_C <- function(a, new_x, leftNode) {
    .Call('_forestryR_update_A_inv_C', PACKAGE = 'forestryR', a, new_x, leftNode)
}

#' @export
update_S_k <- function(prev, next_obs, next_y, left) {
    .Call('_forestryR_update_S_k', PACKAGE = 'forestryR', prev, next_obs, next_y, left)
}

#' @export
update_G_k <- function(prev, next_obs, left) {
    .Call('_forestryR_update_G_k', PACKAGE = 'forestryR', prev, next_obs, left)
}

#' @export
compute_Best_RSS <- function(training_data, lambda, splitting_feat, linear_features) {
    .Call('_forestryR_compute_Best_RSS', PACKAGE = 'forestryR', training_data, lambda, splitting_feat, linear_features)
}

